[project]
name = "au-connect-recommendation-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Minn01", email = "min12200514@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pymongo>=4.17.0",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.1",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
au-connect-recommendation-service = "au_connect_recommendation_service:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
